### ISSUE TITLE
Clean and harmonize jws/main.go/headers.go

### ISSUE THREAD

**Issue by repenno** [lestrrat-go/jwx#122]
Remove package name from const names
Use "name" instead of "method". We do not use "method" per se anymore after all changes, i.e., there is no direct call to any method.
Use GetAlgorithm() instead of Algorithm()
Added PrivateParams as a JSON tag. But if we want flattened we can change asap.

I am trying to get all generate code to look similar and follow a pattern.

**Comment by lestrrat** [comment]
no, please dont rename method names.

**Comment by repenno** [comment]
please check the code and ask for any changes you want

**Comment by lestrrat** [comment]
i hope you don't take this the wrong way but i should tell you that while your involvement has been greatly appreciated, *in general* if you want sweeping style/api changes you should consider forking instead of making prs.

there is no way short of a complete messup on my part that I will merge style/api changes that doesn't fix a real problem.

**Comment by repenno** [comment]
Of course I will not take it the wrong way. No problem. I will make the changes only on my copy of the repo. I will close this PR.
