### ISSUE TITLE
Question: Would it be feasible to exclude "alg: none" at build time?

### ISSUE THREAD

**Issue by srenatus** [lestrrat-go/jwx#189]
Hey there, thanks for this project. It's nice to see a JWx library of good quality. :+1:

Given the frequent issues around "alg: none" in JWT, I was wondering if it would be feasible to exclude the support for that using a build flag.

What do you think, is this worth having and doable? 😃

**Comment by lestrrat** [comment]
Can you be more specific about "exclude the support". I haven't really considered them too deeply, but e.g.
1. Return an error when something like `jws.Verify` is executed
2. Remove the constant jwa.NoSignature
3. Return an error when something like `token.Set("alg", "none")` is used
4. or something else

**Comment by srenatus** [comment]
Thanks for responding so quickly.

On a high level, I would like to pretend we lived in a world where the specs didn't have `alg: none` at all. Concretely, this would mean (1.), (2.) and (3.), I guess 😅I don't know the inner workings here, perhaps a subset of these achieves the same goal?

**Comment by lestrrat** [comment]
Okay, I know the whole `alg: none` being evil and what not, but I'm going to take a step back and ask you the following.

I thought I had included an issue template that asked the users to include code (even if it's pseudo-code) but I guess I only did that for bug report templates. That is my mistake, and I apologize for not putting this up front. I'll address it later, but here's what I wrote else where:

> # To Reproduce / Expected behavior
> Please attach a standalone Go test code that shows the problem, and what you expected to happen.
> If you are asking for an API change or some such which inhibits you from providing a working code, please do your best to come up with a near-valid code.

For the sake of this discussion, I would like to ask you to take some time to come up with how YOU want to use this library, in a way that fits your needs.

Even as somebody who is aware of the `alg: none` problem, I am certainly not going to claim that I know _exactly_ what you want. I can certainly help, but I do not want to guess what you are thinking. And putting it in code clears a lot of things that issues otherwise don't communicate well.

Or to put it more plainly, please show me how you want my library to behave. What I especially want to see:
* (If the API doesn't need to change) Please provide with a test case that should fail.
* (If the API needs to change, or maybe an argument or an option needs to be added) Please provide with a test case that uses the would-be new, imaginary API.

This would save me a few hours of guessing and feeling insecure about what you want.

**Comment by srenatus** [comment]
Thanks for taking time to deal with this here. You are completely right, this is the level of detail we should communicate in -- I'll come back with a more fleshed-out proposal when we actually start using the library. 😃 

This can be closed or kept open as you see fit. 😉

**Comment by lestrrat** [comment]
in #196 there was specific use case request, so I added some tests and turns out `alg: none` was never even allowed when we go through verification (we use a switch case where we check for supported algorithms, and `none` is not one of them). So I believe this issue was never relevant. If you have a specific case where we actually allow `alg: none`, please attach a test case and let us know!
