### ISSUE TITLE
JWS headers with numeric values are parsed as float64

### ISSUE THREAD

**Issue by yaronf** [lestrrat-go/jwx#221]
When I parse a JWS into a Message and then access the headers, any number (e.g. a timestamp in my case, originally an int64) is unmarshaled as float64. This potentially loses precision and is not ideal for security code.

Setting the header:
```go
	_ = headers.Set("ts", time.Now().Unix()) 
```

Reading the header:
```go
	tsi, found := headers.Get("ts")
	ts, ok := tsi.(float64)
	if !found || !ok || !isValidTimestamp(int64(ts)) { // conversion to int64 will round the number :-(
		logger.Debugf("ts: found %v ok %v tsi %T -- %v", found, ok, tsi, tsi)
		return errors.New("Bad ts header")
	}
```

A better solution would be to use the JSON package `UseNumber` facility, then we'd get back a string. See https://stackoverflow.com/a/22346593

**Comment by lestrrat** [comment]
I think my initial thought when I wrote this was that 

1. I don't like that that we lose symmetry when we set, say, an integer, and then when Marshal/Unmarshal an object to and from JSON we get a json.Number back instead of an int, and
2. Those who need exact values in JSON need to use strings anyways -- precision in JSON will vary depending on the platform that parses it, therefore careful coders will store int64 values as string, and parse them back to int64 by hand.

I'm not vehemently against using `json.UseNumber`, but my gut reaction is that if you need precision, you won't be dumping int64s into JWS anyways. I admit that I'm not particularly an expert in JWS: Feel free to prove me wrong, preferably with test code with examples from the wild.

**Comment by yaronf** [comment]
The problem with this approach is that numbers will be marshaled to quoted strings by the JWS `Headers.Set` API. And if the protocol requires a number, you're screwed. This is the case in the protocol I'm working on, [gnap-00](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-00.html) sec. 8.1. 

Yes, I realize that simply adding `json.UseNumber` would be a breaking change.

**Comment by lestrrat** [comment]
So the consumer end of the gnap protocol needs to accept an integer. Okay, I thought you were on the producer side.

The only hard part about this problem is that calls to `encoding/json` are buried deep in the code, and it's everywhere (and I think I would have to change this behavior for the entire `jwx` package so it's uniform) -- so it's not trivial to toggle the use of `json.UseNumber` without, as you say, introducing a breaking change.

**Comment by lestrrat** [comment]
Having said that, would you take a look at #222 ? This was the relatively easy thing to do.

**Comment by lestrrat** [comment]
forgot to ping: @yaronf
