### ISSUE TITLE
How should we format a jwk.Key object?

### ISSUE THREAD

**Issue by debug-ito** [lestrrat-go/jwx#236]
Current documentation (v1.0.5) does not explicitly describe how to format a `jwk.Key` object, I think. For parsing, we can easily figure out we can use `jwk.ParseKey` function from the document, but for formatting, we have basically no idea.

I was able to format a `jwk.Key` by  `json.Marshal`, but is that behavior officially supported? If so, we should mention it in the document.

**Comment by lestrrat** [comment]
I think prior to the great refactor of 2020 (#154 onwards) this used to be more self explanatory, because you needed to work more with the actual underlying types of `jwk.*Key`, and not the more abstract `jwk.Key` type. 

I suppose an example test and a corresponding entry in the README may be much deserved.

**Comment by debug-ito** [comment]
Thanks!
