### ISSUE TITLE
When is the next expected release?

### ISSUE THREAD

**Issue by faraonc** [lestrrat-go/jwx#247]
When is the next expected release?

My team is very interested with this library. It seems like this library have code in master that can enable to parse the token string with verifications option to validate the token e.g. expiration date. This functionality was introduced in this PR https://github.com/lestrrat-go/jwx/pull/220/files

**Comment by lestrrat** [comment]
I've been holding off since I had been pointed out that there were interoperability problems with other libraries. And while this effort is going to continue, the immediate blocker is #234 -- which, I have just been notified that there may be a fix for. So if that goes through, the answer is "soon-ish" :)

**Comment by lestrrat** [comment]
https://github.com/lestrrat-go/jwx/releases/tag/v1.0.6.

Enjoy.

**Comment by faraonc** [comment]
Thanks a lot!
