### ISSUE TITLE
I want to get an object in private claim more easily

### ISSUE THREAD

**Issue by Code-Hex** [lestrrat-go/jwx#332]
Sorry my bad english skills 🙇 

**Abstract**

I want to get an object in private claim more easily.

Currently, If I want to retrieve the objects in private claim as I wanted types, need to create a new token type which is implemented `jwt.Token` interface (like openid package) and pass it to `jwt.Parse` functions with `jwt.WithToken` option.
It's very hard to me to implement this interface to get a single object.

Example payload that object in private claim.

```json
{
  "exp": 1577880060,
  "iat": 1577880000,
  ...
  "profile": {
    "name": "codehex",
    "age": 100
  }
}
```

This is code to understand the "Parse" function's default behavior.
I've retrieved "profile" object as `map[string]interface{}` if not used above ways.

https://play.golang.org/p/7FzKGCHhJZ5

**Describe the proposed solution/change**

I figured it would be useful to be able to write code like this.

```go
type Profile struct {
    Name string
    Age int
}

token := jwt.New(jwt.WithPrivateClaimAs("profile", Profile{}))
t, _ := jwt.ParseString(tokenStr, jwt.WithToken(token))
profile, _ := t.Get("profile")

fmt.Printf("%#v\n", profile) // main.Profile{Name:"codehex", Age:100}
```

jwt package

```go
func New(options ...TokenOption) Token

func WithPrivateClaimAs(name string, v interface{}) TokenOption
```

**Analysis**

- Create a new option to `jwt.Parse` function.
  - I had no idea how to handle the case where multiple objects are included in a private claim.

**Comment by lestrrat** [comment]
Before we talk about yet-to-be-implemented solutions, I think the best approach with the current API is just to do this:

```go
func GetProfile(t jwt.Token) (*Profile, error) {
   v, ok := t.Get("profile")
   var ret Profile
   // traverse v, and populate ret
   return &ret
}
```

This abstracts much of the boilerplate without so much changing any API or behavior.

---

Now, having said that... I don't think your proposed solution is generic enough. Remember that private fields ("claims" in JWT lingo) are present in all of JWE, JWK, JWS, and JWT. We can't just introduce a change like this in JWT only.

One solution I can think of is to an API like this

```go
var v Profile
if err := tok.UnmarshalField("profile", &v); err != nil {
   ...
}
```

We would store the private claims as `json.RawMessage` instead of an object, and only Unmarshal it on demand.

This is going to be backwards incompatible, so we may need to protect it via a global setting:

```go
func init() {
   // globally change the behavior for jws, jwe, jwk, and jwt
   jwx.Settings( jwx.WithPrivateFieldsAsRawMessage(true) ) // meh, bad name ....
}
```

Or maybe even a build tag.

```
go build -tags jwx_private_fields_as_raw_message ...
```

**Comment by lestrrat** [comment]
Hmmm, this new API needs to be different from the current `Get()` in that, it should ONLY be applicable to private fields.

So if I do

```
tok.UnmarshalField(`sub` ...)
```

it should be an error. I mean, I can't support both `tok.Subject()` and `tok.UnmarshalField("sub")` -- otherwise I would have to parse the `"sub"` field AND keep its `json.RawMessage` value, which is just a waste of space.

So the API needs to be named like

```
tok.UnmarshalPrivate(`privateFieldName`, ...)
```

which is okay, but it's going to be annoying that I would need to return an error if it's used against a non-private field :/

**Comment by lestrrat** [comment]
The bigger problem here is that it's not uniform. `tok.Get()` was uniform, because it could be applied to all fields.

If we have a method only for private fields, then the method needs to differentiate between private and non-private, and it's going to be hard to covey that through the method names and what no to the user. Currently I'm not a big fan.

Let me know if you have better ideas.

**Comment by Code-Hex** [comment]
Thanks for your reply.

I had concern the same as your opinion like this. So I proposed solution to specify the token options and pass them to `jwt.New` function.

> The bigger problem here is that it's not uniform.

The details went like this. (Sorry I didn't write down the details.)

```go
func New(options ...TokenOption) Token {
   // process like this in the functional options.
   privateClaimsTypes := make(map[string]interface{})
   privateClaimsTypes["profile"] = Profile{}
   
   return &stdToken{
      mu:   &sync.RWMutex{},
      privateClaims: make(map[string]interface{}),
      privateClaimsTypes: privateClaimsTypes, // Sets type mappings
   }
}

func (t *stdToken) UnmarshalJSON(buf []byte) error {
   t.mu.Lock()
   defer t.mu.Unlock()
   ...
         default:
            if typ, ok := t.privateClaimsTypes[tok]; ok {
               v := reflect.New(typ).Interface()
               if err := t.setDecoded(v); err != nil {
                  return errors.Wrap(err, "failed to set ...")
               }
            } else {
               var decoded interface{}
                if err := t.setDecoded(decoded); err != nil {
                  return errors.Wrap(err, "failed to set ...")
               }
            }
         }
      default:
         return errors.Errorf(`invalid token %T`, tok)
   }
}

func (t *stdToken) setDecoded(tok string, decoded interface{}) error {
      if err := dec.Decode(&decoded); err != nil {
         return errors.Wrapf(err, `failed to decode field %s`, tok)
      }
      if t.privateClaims == nil {
         t.privateClaims = make(map[string]interface{})
      }
      t.privateClaims[tok] = decoded
      return nil
}
```

This way, `tok.Get` will be uniform.

BTW, I used like this way now, but It's not good way for me.

```go
func GetProfile(t jwt.Token) (*Profile, error) {
   v, ok := t.Get("profile")
   if !ok {
      return nil, errors.New("unexpected error")
   }

   b, _ := json.Marshal(v)

   var ret Profile
   err := json.Unmarshal(b, &ret)
   if err != nil {
      return nil, err
   }
   return &ret, nil
}
```

I agree your opinion about a new method `tok.UnmarshalPrivate` (if created)

> it's going to be annoying that I would need to return an error if it's used against a non-private field :/

---

I thought about it for a day, but I couldn't come up with a good idea that would satisfy everything.

I will choice a way to the `GetProfile` function mentioned above if you're still not a fan of my ideas.

thanks.

**Comment by lestrrat** [comment]
>BTW, I used like this way now, but It's not good way for me.

Please elaborate?

---

I don't like the fact that your proposal hooks into `New()`, because then it's a per-object configuration. Why carry that extra information AFTER it has been parsed?

If that option is only used during `Parse()` I guess it would feel better, but then the results of `json.Unmarshal` and `jwt.Parse` would be different ... :/

```go
jwt.Parse(..., tok, jwt.WithCustomField(`x-foo-bar`, ...)) // knows about x-foo-bar
jwt.Unmarshal(..., tok) // knows NOT about x-foo-bar
```

I guess I can live with an ephemeral field in `jwt.stdToken`?

```go
func (t *stdToken) UnmarshalJSON(....) error {
  ...
  t.customFields = nil
}
```

Oh wait, but you *could* potentially do the following, and the parsing results for payload1 and payload2 would differ ...

```go
tok := jwt.New(...)
json.Unmarshal(payload1, &tok)
...
json.Unmarshal(payload2, &tok) // customFields already cleared :/
```

Hmmmmm. That leaves me with "keep this information in a global registry":

```go
jwt.SetCustomField(`x-foo-bar`, ...)

tok1 := jwt.New()
tok2 := jwt.New()
json.Unmarshal(..., tok1) // both tok1 and tok2 will decode x-foo-bar to a custom field type
json.Unmarshal(..., tok2) //
```

So, how about a global (per each jwe, jwk, jws, and jwt packages) registry?

**Comment by Code-Hex** [comment]
I think this library consider for performance to marshal and unmarshal JSON.
But marshal and unmarshal again to retrieve them to a struct seemed to ruin a good part of it.

> Please elaborate?


I see.

> I don't like the fact that your proposal hooks into New(), because then it's a per-object configuration. Why carry that extra information AFTER it has been parsed?

I think that's fine too!

> So, how about a global (per each jwe, jwk, jws, and jwt packages) registry?

**Comment by lestrrat** [comment]
@Code-Hex "Please elaborate?" は「具体的に言うと？」という質問です！使えない理由があるとしたらなんなのかなーと

**Comment by lestrrat** [comment]
さっき一瞬返信したのは間違い。了解です

**Comment by Code-Hex** [comment]
勉強になりました！
相談に乗ってくださってありがとうございました！

**Comment by lestrrat** [comment]
もうコードの骨子はかけてるんですけど、全てのパッケージに同じように展開しないといけないのでちょっと待っててください。あとミーティングが終わるまで作業できないので！ｗ

**Comment by Code-Hex** [comment]
早いw
いや、全然お手すきで大丈夫です。楽しみにしてます！

**Comment by lestrrat** [comment]
とりあえず今あるコードはこちら https://github.com/lestrrat-go/jwx/tree/topic/custom-fields

**Comment by lestrrat** [comment]
@Code-Hex Please check #333, and let me know if it works.

**Comment by Code-Hex** [comment]
@lestrrat It's working!!
Thank you so much :bow:
