### ISSUE TITLE
jwt.ParseRequest returns invalid error

### ISSUE THREAD

**Issue by R70YNS** [lestrrat-go/jwx#458]
Submitting an invalid JWT within the Authorisation header results in different errors based on whether `jwt.ParseRequest` or `jwt.ParseHeader` was called. 

`_, err := jwt.ParseHeader(r.Header, "Authorization", jwt.WithKeySet(XXX))` rightly returns:
`failed to verify jws signature: failed to verify message: crypto/rsa: verification error`
 
`_, err := jwt.ParseRequest(r, jwt.WithKeySet(XXX))` wrongly returns:
```failed to find token in any location of the request (tried: [header keys: "Authorization"])```

It did find the appropriate token from the request, but ignores the error as to continue looking within the form data. This issue would also affect when an invalid JWT is sent within form data.

```go version go1.15.7```

**Comment by lestrrat** [comment]
I can't say for sure without code, but since you are using a `jwk.Set`, you probably don't have a `kid` field in your token and/or key. The requirement for Key ID is [described in options.go](https://github.com/lestrrat-go/jwx/blob/47a4c593218ce49ae0384d26de2bf86d9065bbe6/jwt/options.go#L162-L165) (although now that I look at it it could be worded more explicitly)

Basically the rationale is that when you use a JWKS, you are saying "just choose one that works", and therefore are prone to invalid keys being used, akin to [this situation](https://github.com/lestrrat-go/jwx/blob/main/docs/99-faq.md#why-dont-you-automatically-infer-the-algorithm-for-jwsverify-), so we only allow keys to be used when we know it's the one that you are using.

OTOH, if you are using a jwk.Set with only one jwk.Key in it, you can use `jwt.UseDefaultKey` to bypass this requirement.

**Comment by R70YNS** [comment]
It works fine when I pass a valid key, both using `ParseRequest` and `ParseHeader`. The issue is that the error returned when passing an invalid key via `ParseRequest` is 
```failed to find token in any location of the request (tried: [header keys: "Authorization"])```
however it was able to find the token in the Authorization header. If I change lines `78-82` in `jwt/http.go` to:
```
for _, hdrkey := range hdrkeys {
		tok, err := ParseHeader(req.Header, hdrkey, parseOptions...)
		if err != nil {
			return tok, err
		}
	}
```
When it falls into the if statement, the error is correct: `failed to verify jws signature` but this isn't currently checked and continues to lines 114-129 where strings.Builder is used to specify the token was not found. I understand why this is done, to continue checking the form-data for the JWT on lines 90-94 however the error currently given is misleading as the token was actually found.

**Comment by lestrrat** [comment]
Oh, so the key is _invalid_, and the error is NOT key is invalid, but the error message is "failed to find".
Okay. See, if you gave me some code, it would have been much clearer.

I think the only thing I can do is to change the error message to say "failed find a *VALID* token ...."
Does that work?

**Comment by lestrrat** [comment]
@R70YNS See #461 and if it doesn't work for you, please reopen! Thanks for reporting.
