### ISSUE TITLE
Feedback about major releases

### ISSUE THREAD

**Issue by fabriziomoscon** [lestrrat-go/jwx#528]
Thank you for the library, we have been using it for a long time and it is very useful.
The only feedback we have would be to consider semver for major releases. 
We noticed two breaking changes that were not represented with a major version and in a multi repo project code base it makes it very difficult to upgrading, especially because this library is an indirect dependency for many projects.

We use this doc as a reference for major releases.
https://go.dev/doc/modules/major-version

Thanks again for your important work.

**Comment by lestrrat** [comment]
Which changes?

**Comment by fabriziomoscon** [comment]
We are seeing issue from v0.9.1 to v0.9.2
```
cannot use &alwaysNewHTTPClientOption{} (type *alwaysNewHTTPClientOption) as type *http.Client in argument to jwk.WithHTTPClient
```

that forced us to write this line at the bottom of go.mod:

```
replace github.com/lestrrat-go/jwx => github.com/lestrrat-go/jwx v0.9.1
```

and I also read about breaking changes in v1.1.0: https://github.com/lestrrat-go/jwx/releases/tag/v1.1.0

If you are following semver, that makes me think that breaking changes in v0 were expected because of v0, which is fine.

**Comment by lestrrat** [comment]
You are giving me this after one whole _year_ since the breaking change happened...?

This has been discussed before.

https://github.com/lestrrat-go/jwx/discussions/327#discussioncomment-545750

> Only a handful of users were present for the 5 lonely years that I have been developing this library, and of course, I would have been more careful if this was used by millions.
> As it is, there was hardly anybody, and nobody ever responded to my repeated calls to check if the changes were okay.
>
> This is a HOBBY for me, and this is opensource.
> On the other hand if you participate in the development/discussions from the next time on, of course I will listen. This is all I'm saying.

I'm very glad that you found my work useful, and I'm sure you mean no harm, but to make sure I get this out to everybody else, here's me being blunt:

I'm not saying I don't care about users or semvers, I'm not saying I didn't mess up, but users are not entitled to expect that I should make my **hobby** fit _your_ needs. If this is important to you, _YOU_ keep an eye out for breaking changes, _YOU_ keep track of what changes go in, _YOU_ participate in steering the project so versioning are handled properly.

[Alternatively, you can pay me a 6-digit salary and I will of course make sure this library is perfect](https://web.archive.org/web/20210704022108/https://github.com/Marak/faker.js/issues/1046)

**Comment by fabriziomoscon** [comment]
My feedback wasn't meant to be negative, sorry if it sounded that way. We are helping with PRs many open source repos that we use. I am sorry we didn't contribute to your repo before.
I also personally maintain open source libraries mostly on my own, and I know it's a though job/hobby.

**Comment by lestrrat** [comment]
Point taken, and you don't need to apologize, but the main point here is that you came strolling down and

* Did not provide specifics (I spent a couple of hours making sure recent releases didn't have any problems b/c of this)
* Did not provide feedback for something actionable (what am I supposed to do with a one year old release... apologize?)
* Did not offer to help or pay, but merely "advised" and tried to teach me semvers.

Come on, just think what happens if somebody you don't know came up to you and did this.

Anyways, as I wrote, I don't doubt your good intentions. This is case closed, please don't reply further on this issue unless there's something constructive/actionable to be said. Thank you.
