### ISSUE TITLE
Add a way to compare jwk.Key

### ISSUE THREAD

**Issue by anatol** [lestrrat-go/jwx#539]
I need a way to check whether 2 arrays of `jwk.Key` intersect. And to achieve it I iterate over those and compare the keys.

I did not find any way to compare `jwk.Key`s. It would be great to have something like `Equal()` function at that interface. And the implementation would compare essential key fields - the same fields that are used for `Thumbprint()`.

**Comment by lestrrat** [comment]
I don't think there exists a standard way to compare JWKS. Of course, I may have just missed it. Is there one?

Your proposal does make some sense, but I'm not sure it's something that should be available as a standard way unless it really _is_ the standard way to compare JWKSes.

**Comment by lestrrat** [comment]
Oh, wait,. I read it as jwk.Set, not jwk.Key. sorry. Re-reading...

**Comment by lestrrat** [comment]
> And the implementation would compare essential key fields - the same fields that are used for Thumbprint().

That means that using the current implementation of `Thumbprint()` already does exactly what you are asking for, no?

I'm a bit weary of adding `Equals()` because the definition of equality may differ between you and others. You may think that keys are equal if keys for the thumbprints match, but maybe others want complete equality for all fields.

**Comment by anatol** [comment]
comparing `Thumbprint()` is something similar to what I need. Though is does a lot of unneeded computation such as converting types, calculating hash. Comparing the underlying fields would be much cheaper.

Does the jwx spec say anything about keys equality?

**Comment by lestrrat** [comment]
> Does the jwx spec say anything about keys equality?

Not that I know of, at least not when I was reading the specs in-and-out.

**Comment by lestrrat** [comment]
So, just FYI, my basic stance on these libraries is to provide "easy-to-use" APIs.
(easy-to-use includes providing a sane API, safety mechanisms to stop users doing silly things, name things correctly, etc)

And my take on ease of use and performance is that, you _usually_ have to give up one for the other.
Aaaand in general if I have to make a choice between the two,  I go for ease of use.

I'm just putting this upfront, so you don't feel like I'm rejecting everything you are proposing... there _is_ logic to the madness!

It is quite possible that somebody other than myself, you or somebody else, can come up with a much more clever way to provide the same ease of use without sacrificing performance, so if you can, please let me know!

**Comment by treeder** [comment]
I'd like to see this too. Would a field by field comparison make sense? Minus things like "kid".

**Comment by lestrrat** [comment]
I think this one is hard to provide as a standard API because the definition of equality of JWK is not defined.

For example, suppose a `key.Equal(anotherKey)` is provided. I _personally_ would define JWK equality as "A key is equal to another key as long as the mathematical result of signature/encryption are the same" -- which is something that the result of the keys' thumbprints can be used for. Therefore my `Equal()` would be implemented in terms of `key1.Thumbprint() == key2.Thumbprint()`

But at least as of your comment you would want a field-by-field comparison. so even if key1 and key2 have the same core characteristics (such as EC key's "crv", "x", and "y"), if key1's "op" is "enc" and key2's "op" is "sig", they would be considered different keys.

Furthermore, what happens if this field by field comparison involved user-defined fields that could potentially be nested? i.e. `{"x-custom-field": { .... }}`. I'm not saying these can't be compared, but the definition of equality must be defined in a robust way that works for most everybody too.

So you see, that even between you and I we have different definitions of equality.
And since there isn't a consensus as to the definition of equality for JWKs,  I feel that it could be misleading / confusing to provide an API that sounds as if We Do The Right Thing, like `Equal()`, as a standard tool.

---

I'm open to the possibility that I'm just missing something simple, so please feel free to feed me more info / suggest a better way if you want.

**Comment by treeder** [comment]
Specifically, I want to compare public keys.

**Comment by lestrrat** [comment]
Yeah, but what's your definition of a comparison operation against public keys?

**Comment by treeder** [comment]
Thanks for the explanation. Would it be possible to compare public keys only?

**Comment by lestrrat** [comment]
@treeder It's not a matter of pirvate/public. What's your definition of equality for public keys?

**Comment by treeder** [comment]
I'm thinking similar to the way you a user's blockchain public key (aka, their address) is easily sharable and comparable and nobody else can have the same public key.  I assumed that something similar could be done here, but I could be wrong.

**Comment by anatol** [comment]
> @treeder It's not a matter of pirvate/public. What's your definition of equality for public keys? 

My definition of equality is "keys are equal iff their thumbprints are equal (without taking hash collision into account)". So all the fields that are used for thumbprint generation need to be used in Equal method.

**Comment by lestrrat** [comment]
@treeder I'm not a blockchain person, but I suspect that the public key is part of a BLOCK (or a chain, I don't know), rather than the public key itself, akin to JWS's `jwk`/`jku` fields. That's a property of the data being signed, not the key.

**Comment by lestrrat** [comment]
@anatol I can dig that, but since `Thumbprint()` is already available, I don't see why you can't just do `bytes.Equal(key1.Thumbprint(), key2.Thumbprint())`. If there are cases where a presence of `Equal() bool` for duck-typing purposes would help (other than saving a few keystrokes) exist, I think it's reasonable to implement. But since it would be exactly equal to comparing Thumbprints, I'd like to know concrete use-cases.

**Comment by treeder** [comment]
It's quite a bit of code to do the comparison, assuming I have this right:

```go
        thumb1, err := k.Thumbprint(crypto.Hash(0))
	if err != nil {
		return err
	}
	thumb2, err := input.SignedBy.Thumbprint(crypto.Hash(0))
	if err != nil {
		return err
	}
	if bytes.Equal(thumb1, thumb2) {
		matched = true
		break
	}
```

So a single line `Equal(k1, k2) bool` function would certainly be convenient (and provide a more obvious way of doing this).

**Comment by lestrrat** [comment]
@treeder I thought you wanted something else, since you mentioned checking field by field.

**Comment by lestrrat** [comment]
Okay, so I had forgotten that Thumbprint can return errors, and I guess 10 lines is better written as 1. Here's a sample (#977) I whipped up just now. Please let me know
