### ISSUE TITLE
Verify JWT signature after JWT has already been parsed

### ISSUE THREAD

**Issue by atzawada** [lestrrat-go/jwx#678]
I'm looking for a way to verify the signature of a JWT with a JWK set after it has already been parsed into a `jwt.Token` struct. For my use case, I would like to keep the parsing and validation logic separate, so I need a way to either validate the signature when I have the `jwt.Token` form or I need a way to get the string representation of the JWT so I can send it back to `jwt.Parse`. Any suggestions?

Thanks!

**Comment by lestrrat** [comment]
What do you want to do in between the parsing and verification? [Please provide code](https://github.com/lestrrat-go/jwx/blob/develop/v2/.github/CONTRIBUTING.md#please-include-pseudocode-for-any-technical-issues).

Also, this is a very minor detail, but at least in this library ["validation" and "verification" are two separate steps](https://github.com/lestrrat-go/jwx/blob/develop/v2/docs/01-jwt.md#terminology) Please be explicit in which one you are referring to in order to avoid confusion :)

**Comment by atzawada** [comment]
Thanks for the quick response!

We want to be able to perform _verification_ of the JWT's signature separately, sorry for the confusion.

I work on an application that uses JWT as a signing and storage mechanism for software supply chain events. I'm not sure how much of the code I can really provide since it is an internal project, but the gist is this:

We have a client that is composed of two pieces, a store (fetcher) and a validator. the store retrieves a list of JWTs via HTTP, which the client then does some manipulation on, and then the JWTs are passed into the validator that checks the signatures and produces the final list of valid JWTs.

We would like to keep the retrieval and validation/verification mechanisms separate as the project may eventually be open sourced, and we would like users to plug in their own retrieval/validation logic, or even open up to use non-JWT implementations.

**Comment by lestrrat** [comment]
> I'm not sure how much of the code I can really provide since it is an internal project,

Even if that's the case, you should be able to provide pseudocode. Please understand that I do this guessing game to understand what reporters are talking about for **_every single_** issue that comes without code. I know you're not trying to be mean or anything, but having to decipher everybody's intentions about their code through conversation _really_ gets to me.

Please be a good example for the others and provide code when requested, especially when I have been so clear that pseudocode is totally fine in the contribution guidelines.

---

If I read your description correctly, there's no way to do this in v1. But if you are willing to use v2 and the following sequence diagram matches your needs, you can leverage the  [`jws.KeyProvider`](https://github.com/lestrrat-go/jwx/blob/develop/v2/docs/01-jwt.md#parse-and-verify-a-jwt-using-arbitrary-keys) mechanism. 

```mermaid
sequenceDiagram
  autonumber
  actor User
  participant jwt.KeyProvider
  participant jwt.Parse
  User->>jwt.Parse: signed JWT
  jwt.Parse->>jwt.KeyProvider: Request for verification key
  Note over jwt.KeyProvider: "Receives jwt.Token,<br />protected headers, et al"
  jwt.KeyProvider->>jwt.Parse: Provide key(s) to verify with
  jwt.Parse->>User: Return verified payload
```

If there's something more to this workflow that I'm missing then I'm sorry I didn't understand, but please include code.

**Comment by atzawada** [comment]
Sorry to cause any confusion, here is some pseudo-go code that would hopefully help you understand our use case. Sorry for the alphabet soup but I am trying to keep this as generic as possible.

We have our client code with the following interfaces
```go
type DTOStore interface {
	DTOs(artifact string) (dtos []DTO)
}

type DTOValidator interface {
	Validate(dto DTO) bool
}

type DTO interface {
	CustomField() string
	AnotherCustomField() string
}
```

And a client implementation that looks like this:
```go
type Client struct {
	Store     DTOStore 
	Validator DTOValidator
}


func (c *Client) ValidateDTOsForArtifact(artifact string) (validDTOs []DTO) {
	dtoResponse, err := c.Store.DTOs(artifact)

        // Do some additional processing here

	for _, dto := range dtoResponse {
		result := c.Validator.Validate(dto)
                if !result {
                        continue
                }

		validDTOs = append(validDTOs , dto)
	}

	return validDTOs
}
```

For the DTO, store, and the validator, we have a default JWT-based implementation:

```go
// DTO implementation
type JWTBasedDTO struct {
	JWT jwt.Token
}
// Also implements DTO interface

func NewJWTBasedDTO(jwtString string) (store.DTO, error) {
	jwt, err := jwt.Parse([]byte(jwtString))
	if err != nil {
		return JWTBasedDTO{}, err
	}

	return JWTBasedDTO {
		JWT: jwt,
	}, nil
}

// Store implementation
type JWTBasedDTOStore{}

func (f *JWTBasedDTOStore) DTOs(artifact string) (DTOs []DTO, err error) {
	// Authenticate and retrieve JWTs and supporting structures from http API
        apiResult := // API response, contains list of JWTs

	for _, result := range apiResult {
		dto, err := NewJWTBasedDTO(result.JWT) // Passing in the string JWT to create a jwt.Token struct

		DTOs := append(DTOs, dto)
	}

	return DTOs, nil
}

// Validator implementation

type JWTBasedDTOValidator struct {
	JWKs *jwk.Set
}

func (v JWTBasedDTOValidator) Validate(dto DTO) (bool, error) {
	dtoJWT := (dto .(JWTBasedDTO)).JWT // Cast to JWT implementation and retrieve jwt.Token
	
       // Take some step here to signature verification using the jwt.Token and the jwk.Set
	
	// Perform some non-standard JWT validation on custom fields

	return err == nil, err
}
```

Here is an interaction diagram to help as well:
![JWT_impl_flow](https://user-images.githubusercontent.com/32112934/162116152-21946ac2-558d-4551-83e4-2ccdace92efd.png)

**Comment by lestrrat** [comment]
Ah, okay.

There are some details that still escape me, but if I'm reading this right, this is a case where you would have to carry the raw signed JWT payload all the way through. Probably your `JWTBasedDTO` needs to be:

```go
type JWTBasedDTO struct {
   JWT jwt.Token
   RawJWT string // or []byte
}
```

Then you can do the verification wherever/whenever you want.
(I have a slight feeling you might be able to combine `jws.Parse()` and the like for your usecase, but I'm not entirely sure -- here, I assumed that you don't want to deal with JWS)

---

That's my answer, but let me elaborate why `jwt.Token` doesn't have a `(jwt.Token).Verify()`

signed JWT is a JWS message. The JWS message uses the "protected headers" among other things to create the signature. the protected headers is a _serialized version of a JSON object/hash_.  When we verify the signature, we recreate the signature from our inputs, and compare it against the signature they sent us.

Now the trick is that the protected headers are _serialized_. This means that we need to know the exact serialization format to perform verification afterwards -- i.e. we need to recreate the serialized protected header byte sequence from the data that we parsed.

This is hard because for a given JSON object, say `{"foo": "bar", "baz": 3}`, any of the following serializations are valid (among many more):

```
{"foo":"bar","baz":3}
{"baz":3,"foo":"bar"}
{"foo:"bar",
  "baz":3}
{      "foo":                         "bar",                 "baz":                          3 }
```

It is up to the signer to decide which serialization they use for signing. The serialized string is then sent to the client in base64 encoded format. Once we parse a token, though, we lose this serialization, and we can't recreate it programmatically.

Also, there's a problem of scope. Even if the user wanted to get to the JWS protected headers from `jwt.Parse()`... is this right? Do you store the copy of the **JWS** protected headers in the **JWT**?

Even if you could carry the copy of the JWS protected headers in a JWT, what do you do when you have a `jwt.Token` that you got as a result of simply marshaling a JSON string? Should these behave differently? Does the user need to take different branches depending on the token's state? Lots of questions to be answered, right?

So, that all leads this: In order to allow verifying the token much later than `jwt.Parse()`, we would need to keep the copy of the raw JWS protected headers. This is a burden in terms of API design and forces the user to have to learn more about the internals of a `jwt.Token`. Thus, we don't support this mode, and if you want to verify later, you are going to need to carry the raw signed JWT payload yourself.

**Comment by atzawada** [comment]
> There are some details that still escape me, but if I'm reading this right, this is a case where you would have to carry the raw signed JWT payload all the way through.

Yeah, I think that's where I am ultimately headed with this, will probably have to store the `jwt.Token` and the raw JWT string in the DTO structure.

My knowledge of JWS isn't overly great, but I would agree with the statement that tracking the JWS header information should not be part of the JWT functionality in this module. I guess the only improvement I could see is if the `jwt.Token` carried around the raw JWT string with it to make available down the line, but I understand that functionality is probably confined to this unique situation and would not make sense for the majority of use cases.

Thanks for your help!

**Comment by lestrrat** [comment]
> I guess the only improvement I could see is if the jwt.Token carried around the raw JWT string with it to make available down the line

Yeah, I understand the sentiment, but here's the tricky bit:

```go
tok1 := jwt.New()
json.Unmarshal(data, tok1) // simple JSON payload

tok2, _ := jwt.Parse(...) // signed JWT payload
```

Now, further down the road, these two tokens would behave different behavior:

```go
tok1.Verify(...) // wait, tok2 works, but not tok1
tok2.Verify(...) // wait, what if tok2 had extra parameters set that changes the protected headers?
json.Marshal(tok) // wait, use the _new_ headers in token, or respect the initial protected headers?
```

So I agree that it's a bit frustrating from the user's side, but I'd argue that the RFC is flawed in that while JWT would almost always require signing, signing is NOT part of JWT, but instead it's wrapped in a separate mechanism which is JWS

(as a bonus: what happens if your payload was a JWT that is JWE-encrypted, then JWS-signed? :)
