### ISSUE TITLE
failed to parse jws: failed to unmarshal jws message: required field "signatures" not present

### ISSUE THREAD

**Issue by kishvanchee** [lestrrat-go/jwx#736]
Thank you for the library. I have a minor issue which I feel can be resolved if I could understand the library better. I am trying to decode a token generated by another service. The token is generated using this library - [python-jose](https://github.com/mpdavis/python-jose/) I am trying out the example shown in the README since that's the same process used to encode the data.

**Describe the bug**

In Python, copy pasting from the library README

```python
>>> from jose import jwt
>>> token = jwt.encode({'key': 'value'}, 'secret', algorithm='HS256')
u'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ2YWx1ZSJ9.FG-8UppwHaFp1LgRYQQeS6EDQF7_6-bMFegNucHjmWg'

>>> jwt.decode(token, 'secret', algorithms=['HS256'])
{u'key': u'value'}
```
Here is what I have tried in Go.

```go
package main

import (
	"encoding/base64"
	"github.com/lestrrat-go/jwx/v2/jwa"
	"github.com/lestrrat-go/jwx/v2/jwt"
	"log"
)

func init() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
}

func main() {
	
	var JWT_ALGORITHM = jwa.SignatureAlgorithm("HS256")
	var JWT_SECRET = "secret"

	token := "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ2YWx1ZSJ9.FG-8UppwHaFp1LgRYQQeS6EDQF7_6-bMFegNucHjmWg"

	decodedString, _ := base64.StdEncoding.DecodeString(token)
	{
		verifiedToken, err := jwt.Parse([]byte(token), jwt.WithKey(JWT_ALGORITHM, JWT_SECRET))
		if err != nil {
			log.Println("failed to verify JWS: %s\n", err)
		}
		log.Println("verified token", verifiedToken)
		_ = verifiedToken
	}
	{
		verifiedToken, err := jwt.ParseString(token, jwt.WithKey(JWT_ALGORITHM, JWT_SECRET))
		if err != nil {
			log.Println("failed to verify JWS: %s\n", err)
		}
		log.Println("verified token", verifiedToken)
		_ = verifiedToken
	}
	{
		verifiedToken, err := jwt.Parse(decodedString, jwt.WithKey(JWT_ALGORITHM, JWT_SECRET), jwt.WithValidate(false))
		if err != nil {
			log.Println("failed to verify JWS: %s\n", err)
		}
		log.Println("verified token", verifiedToken)
		_ = verifiedToken
	}
	{
		verifiedToken, err := jwt.Parse(decodedString, jwt.WithKey(JWT_ALGORITHM, JWT_SECRET))
		if err != nil {
			log.Println("failed to verify JWS: %s\n", err)
		}
		log.Println("verified token", verifiedToken)
		_ = verifiedToken
	}
}
```
Output
```
❯ go run ./main.go
2022/05/10 12:07:15 main.go:25: failed to verify JWS: %s
 could not verify message using any of the signatures or keys
2022/05/10 12:07:15 main.go:27: verified token <nil>
2022/05/10 12:07:15 main.go:33: failed to verify JWS: %s
 could not verify message using any of the signatures or keys
2022/05/10 12:07:15 main.go:35: verified token <nil>
2022/05/10 12:07:15 main.go:41: failed to verify JWS: %s
 failed to parse jws: failed to unmarshal jws message: required field "signatures" not present
2022/05/10 12:07:15 main.go:43: verified token <nil>
2022/05/10 12:07:15 main.go:49: failed to verify JWS: %s
 failed to parse jws: failed to unmarshal jws message: required field "signatures" not present
2022/05/10 12:07:15 main.go:51: verified token <nil>
```
Go version
```
❯ go version
go version go1.18.1 linux/amd64
```

**Additional context**
We are encoding a dictionary containing some information which will be decoded and used. This feels straightforward using the existing Python library but there seems to be some differences between that library and your library. Would appreciate any help possible.

**Comment by lestrrat** [comment]
@kishvanchee 

## Short answer

The main problem you have is that symmetric keys are represented as `[]byte`, not string. So converting it to `[]byte` would do the trick.

```go
verifiedToken, err := jwt.Parse([]byte(token), jwt.WithKey(JWT_ALGORITHM, []byte(JWT_SECRET)))
                                                                       // ^^^^^^
```

## Longer answer

In jwx, keys can either be `jwk.Key`, or [raw keys](https://github.com/lestrrat-go/jwx/blob/develop/v2/docs/04-jwk.md#raw-key). Raw keys can be `*rsa.PrivateKey`, `*ecdsa.PrivateKey`, and others. This allows users to easily plugin the keys that they have into jwx -- for example, you could have used `github.com/lestrrat-go/jwx/v2/jwk` to read from a JWKS available on a remote server, or perhaps you have raw `*ecdsa.PrivateKey` laying around in your code. You could shove either. That's why `jwk.WithKey()` allows `interface{}` into its second argument.

Now, the symmetric key doesn't necessarily have to be a valid string -- it could be a sequence of random bytes. That's why it accepts `[]byte`. In your case, you chose a secret that conveniently matched the word `secret` as ASCII characters, but ... yeah, symmetric keys need to be a sequence of bytes :)

## Nit picks

Your error logs look funky because you are using `fmt.Println` instead of `fmt.Printf`. `fmt.Println` does not interpolate `%` patterns :)

**Comment by kishvanchee** [comment]
@lestrrat thank you, that was helpful. That solved my problem.

Thank you for the nitpick. That's something new for me. :)

Thank you again for the library.
