### ISSUE TITLE
move internal/iter to the iter package for convenient codegen

### ISSUE THREAD

**Issue by mxfactorial** [lestrrat-go/jwx#818]
**Abstract**

interface consumers cant use mocks from `mockgen -destination ./mocks/mock.go github.com/lestrrat-go/jwx/jwk Key` when `HeaderVisitor` [aliases](https://github.com/lestrrat-go/jwx/blob/19cd6e04796a754a5c74964e64ba1df62d172105/jwk/interface.go#L116) a type imported from an [internal](https://github.com/lestrrat-go/jwx/blob/19cd6e04796a754a5c74964e64ba1df62d172105/jwk/interface.go#L9) package

**Describe the proposed solution/change**

not urgent as we can write our own interfaces, but please consider moving `internal/iter` to the `iter` package for convenient codegen:

1. https://github.com/lestrrat-go/iter/pull/5
2. https://github.com/lestrrat-go/jwx/pull/817

**Comment by lestrrat** [comment]
ah scratch my comment on the pr.

**Comment by lestrrat** [comment]
I've been pondering about it, but I have this nagging feeling that this is not what I want to do.
The immediate problem at hand is the mockgen, and I would like to fix that for you. But I have this feeling that the "correct" way would be to do something about those interfaces -- i.e. do I need it? Do the users need it? Can it be simply un-exported? Can we change it somehow so that they are more meaningful?

And in this line of though I'm thinking this may be something we need to  tackle for v3.

Still undecided though. I haven't been able to come up with anything concrete as of yet

**Comment by mxfactorial** [comment]
closed the prs

do you need `internal`?

**Comment by lestrrat** [comment]
@mxfactorial internal was needed way back when, but I'm not 100% certain we do now.
For v2 I did revamp the entire "public" API, but for v3 I should probably revisit these things that are creeping out into the public API and decide their necessity and/or actual implementation.

**Comment by mxfactorial** [comment]
option 2: patch with `find ./ -type f -exec sed -i '' 's/internal\//pkg\//g' {} \; && mv internal pkg`

remove `''` for gnu

**Comment by lestrrat** [comment]
Yes and no: that's absolutely fine for your purposes, but my purpose for thinking this for v3 and not v2 is so that we make changes without breaking the public API (accidentally or not), so probably not a choice. I also want to take the opportunity to remove unnecessary public APIs if they are not really necessary (not that I have a particular offender in mind yet) -- but I want to think about this and other packages that maybe in the same boat within this module.
