### ISSUE TITLE
The order of selecting correct key to verify signature

### ISSUE THREAD

**Issue by matino** [lestrrat-go/jwx#852]
First of all, thank you for all the amazing work!

I have a question regarding parsing the JWT with `jws.WithRequireKid(false)` option:
```
jwt.Parse(token, jwt.WithKeySet(keySet, jws.WithRequireKid(false)))
```

My use case is, that most of the time, the `kid` will be present, in very few cases, the `kid` will be missing. Currently, with `jws.WithRequireKid(false)`, the code always iterates over all the keys, no matter if the `kid` is present or not. This is not really efficient.

A potential optimisation could be introduced, that always gets the key by the `kid`. Only if the key is not found - try all the keys.
Let me know if this an approach in the good direction - I'll be happy to submit a PR :)

**Comment by lestrrat** [comment]
I'm not saying that it isn't, but at the same time I'm not convinced that what you suggest is an optimization, because I haven't been presented with evidence that most of times the `kid` will be present. I'm willing to be convinced otherwise. For the time being though, by reading the RFC and seeing the examples that are around in my view I determined that I could not optimize for the presence of `kid`, and that's why it's the way it is.

For your case, you are free to write your own optimized version of a [KeyProvider](https://github.com/lestrrat-go/jwx/blob/develop/v2/examples/jwt_parse_with_key_provider_example_test.go) that is optimized to your needs. I think this would solve your problems?

**Comment by matino** [comment]
Thanks for a quick response @lestrrat.

I think that the performance penalty coming from iterating over all the keys and finding the matching `kid` is minimal compared to actual verification, but this is only my feeling :) 

`KeyProvider` looks fine, it's good to know that there's a workaround available. Thanks!
