### ISSUE TITLE
Expose Registering new JWK types

### ISSUE THREAD

**Issue by decentralgabe** [lestrrat-go/jwx#912]
**Abstract**
I'd like to experiment with Post Quantum signature schemes using JWKs. There are a number of IETF drafts that enable this possibility:
- https://datatracker.ietf.org/doc/draft-ietf-cose-dilithium/
- https://datatracker.ietf.org/doc/draft-ietf-cose-falcon/
- https://datatracker.ietf.org/doc/draft-ietf-cose-sphincs-plus/

**Describe the proposed solution/change**
The ask would be to expose a method similar to [RegisterCurve](https://github.com/lestrrat-go/jwx/blob/develop/v2/internal/ecutil/ecutil.go#LL19C1-L19C1) for experimental key types and signature schemes.

Additionally there would need to be support for these types in [functions like this](https://github.com/lestrrat-go/jwx/blob/develop/v2/jwk/jwk.go#L44), and complementary signing code.

I would recommend enabling this as an experimental feature, similar to the build tag solution for secp256k1 support today.

**Analysis**
Use a different library for signing with these keys/signature algorithms which would make me sad 😢 

**Additional context**
If there's a way to extend the library without forking today I missed - please let me know.

**Comment by lestrrat** [comment]
I briefly looked at this before, but if I understand correctly you don't need to register a _JWK_.

It's the signer/verifier and encrypter/decrypter that needs to be [registered](https://github.com/lestrrat-go/jwx/blob/develop/v2/docs/02-jws.md#using-a-custom-signingverification-algorithm) because the object that
handles the process is triggered by looking at the algorithm name. But the jwx framework the key is
just an opaque object until the signer/verifier/encrypter/decrypter sees it, at which point the
algorithm may dictate a particular type of JWK

So as far as the original question in the title goes, you don't need to register a JWK type and there's already code to register algorithms  (but yes, apparently [we have a bug](https://github.com/lestrrat-go/jwx/issues/910) -- also see #911). 

---

There could be some improvement in `FromRaw`, but I'm not immediately convinced that it's _necessary_ to achieve what you want. At the moment I believe it's a separate issue from allowing algorithms not present in the JOSE RFCs.

**Comment by decentralgabe** [comment]
Thanks @lestrrat you're right as usual 😄 

I put up a PR in my repo that follows the pattern from your docs -- https://github.com/TBD54566975/ssi-sdk/pull/364/commits/a5d60fbcd229c5257524dbd3eae9d568e53d4abd#diff-e90df833f7a92629e6a170157818c5ac1779d6dfe6df2c184aee39323f27c1cb

It's not working because of the bug you noted, which the fix in #911 should address.

Closing...

**Comment by lestrrat** [comment]
@decentralgabe thanks, since by coincidence at least two people need the same functionality in #911 at the same time, I should just merge it :)

**Comment by decentralgabe** [comment]
@lestrrat should I open up a new issue about the `jwk.Key` interface? it's getting fairly ugly in our code to work around supporting key types supported by the interface and those not in it. It would be nice if consumers of this lib could add additional key types.

**Comment by lestrrat** [comment]
@decentralgabe Yes, and please provide (pseudo)code. In your case I don't understand (yet) the reason why you would need to workaround so much. I'd say code for the version that's giving you problems, and a proposed new code that makes it better would make it much easier.

**Comment by decentralgabe** [comment]
After thing a bit further, it's not necessary, but it does make the code a lot cleaner/simpler.

For example: converting between `crypto.Public/PrivateKey` is streamlined, instead of needing to write an abstraction to handle the keys that `jwk.FromRaw` covers and other keys. 

It is probably a better design to not be too tightly coupled to this library's behavior anyway - so I'm fine with keeping things as-is.

**Comment by lestrrat** [comment]
@decentralgabe Not sure exactly what you are intending with a "streamlined" approach, but in general ultimately `crypto` and `jwx` are separate projects and separate code bases, so the conversion between the two will always need some sort of adapter -- therefore my immediate reaction is that it's always going to be messy going back and forth between the two. I don't know, again, I'm not sure what exactly is going on in your code.

If you indeed have a better solution I'm interested, I just need some concrete examples. Anyways, no pressure, let me know when/if you feel like you want to show me some code :)

**Comment by lestrrat** [comment]
This should be doable in v3 since #1012. Closing
